apiVersion: v2
name: portainer-agent
description: A Helm chart for Portainer Agent
type: application
version: 1.0.0
appVersion: "2.29.0"
icon: https://portainer.io/images/logo.svg
keywords:
  - portainer
  - agent
  - kubernetes
  - edge
home: https://www.portainer.io
sources:
  - https://github.com/portainer/portainer
maintainers:
  - name: Portainer
    email: platform-team@portainer.io
    url: https://www.portainer.io
annotations:
  category: Infrastructure
  artifacthub.io/changes: |
    - Initial release of the consolidated Portainer Agent chart
  artifacthub.io/images: |
    - name: portainerci/agent
      image: portainerci/agent:develop