apiVersion: v1
kind: Service
metadata:
  name: {{ (list (include "edge.fullname" .) "headless" | join "-") }}
  labels:
    {{- include "edge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  selector:
    {{- include "edge.selectorLabels" . | nindent 4 }}
