{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "portainer-agent.serviceAccountName" . }}
  labels:
    {{- include "portainer-agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "portainer-agent.fullname" . }}
  labels:
    {{- include "portainer-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "secrets", "namespaces", "nodes", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "statefulsets", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "portainer-agent.fullname" . }}
  labels:
    {{- include "portainer-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "portainer-agent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "portainer-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }} 